#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

LABEL_BOT="com.devin.claude-bot"
LABEL_CHANNEL="com.devin.claude-channel"
HOOK_SRC="$SCRIPT_DIR/claude-channel/discord-restart-notify.sh"
HOOK_DST="$HOME/.claude/hooks/discord-restart-notify.sh"
SETTINGS="$HOME/.claude/settings.json"

echo "=== claude-discord-bot install ==="

# 0. Capture current shell environment
USER_HOME="$HOME"
USER_SHELL="$(basename "$SHELL")"
USER_PATH="$PATH"

TMUX_PATH="$(command -v tmux 2>/dev/null || true)"
if [[ -z "$TMUX_PATH" ]]; then
  echo "[error] tmux not found in PATH. Install tmux first." >&2
  exit 1
fi

CLAUDE_PATH="$(command -v claude 2>/dev/null || true)"
if [[ -z "$CLAUDE_PATH" ]]; then
  echo "[error] claude not found in PATH. Install Claude Code first." >&2
  exit 1
fi

echo "[env] HOME=$USER_HOME"
echo "[env] SHELL=$USER_SHELL"
echo "[env] tmux=$TMUX_PATH"
echo "[env] claude=$CLAUDE_PATH"

# 1. Build
echo "[build] Building claude-bot..."
cd "$PROJECT_DIR"
if ! command -v go &>/dev/null; then
  echo "[error] go not found in PATH. Install Go first." >&2
  exit 1
fi
go build -o claude-bot ./cmd/claude-bot
echo "[build] Done"

# 2. Stop existing services
for label in "$LABEL_BOT" "$LABEL_CHANNEL"; do
  if launchctl list "$label" &>/dev/null; then
    launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
    echo "[launchd] Stopped: $label"
  fi
done

# 3. Set script permissions
chmod +x "$SCRIPT_DIR/bot/run-bot.sh"
chmod +x "$SCRIPT_DIR/claude-channel/run-channel.sh"
chmod +x "$SCRIPT_DIR/claude-channel/discord-restart-notify.sh"

# 4. Save environment snapshot (sourced by run-*.sh)
ENV_SNAPSHOT="$SCRIPT_DIR/env.generated.sh"
cat > "$ENV_SNAPSHOT" <<EOF
# Auto-generated by install.sh at $(date '+%Y-%m-%d %H:%M:%S')
# Captures the installing user's shell environment.
INSTALL_HOME="$USER_HOME"
INSTALL_SHELL="$USER_SHELL"
INSTALL_PATH="$USER_PATH"
INSTALL_TMUX="$TMUX_PATH"
INSTALL_CLAUDE="$CLAUDE_PATH"
EOF
echo "[env] Saved environment snapshot: $ENV_SNAPSHOT"

# 5. Generate LaunchAgent plist files (inject PATH from install time)
mkdir -p "$USER_HOME/Library/LaunchAgents"

generate_plist() {
  local label="$1" script="$2" log_name="$3" dest="$4"
  cat > "$dest" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${script}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${USER_HOME}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${USER_HOME}/Library/Logs/${log_name}.stdout.log</string>
    <key>StandardErrorPath</key>
    <string>${USER_HOME}/Library/Logs/${log_name}.stderr.log</string>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${USER_PATH}</string>
        <key>HOME</key>
        <string>${USER_HOME}</string>
    </dict>
</dict>
</plist>
PLIST
}

generate_plist "$LABEL_BOT" "$SCRIPT_DIR/bot/run-bot.sh" "claude-bot" \
  "$USER_HOME/Library/LaunchAgents/$LABEL_BOT.plist"
generate_plist "$LABEL_CHANNEL" "$SCRIPT_DIR/claude-channel/run-channel.sh" "claude-channel" \
  "$USER_HOME/Library/LaunchAgents/$LABEL_CHANNEL.plist"
echo "[launchd] Generated plist files"

# 6. Install Claude Code SessionStart hook
mkdir -p "$(dirname "$HOOK_DST")"
ln -sf "$HOOK_SRC" "$HOOK_DST"
echo "[hook] Linked: $HOOK_DST"

if [[ -f "$SETTINGS" ]]; then
  HOOK_CMD="$HOOK_DST"
  HAS_HOOK=$(jq --arg cmd "$HOOK_CMD" '
    .hooks.SessionStart // [] | map(.hooks[]? | select(.command == $cmd)) | length
  ' "$SETTINGS")

  if [[ "$HAS_HOOK" == "0" ]]; then
    jq --arg cmd "$HOOK_CMD" '
      .hooks.SessionStart = (.hooks.SessionStart // []) + [{
        "matcher": "",
        "hooks": [{"type": "command", "command": $cmd}]
      }]
    ' "$SETTINGS" > "$SETTINGS.tmp" && mv "$SETTINGS.tmp" "$SETTINGS"
    echo "[hook] Added SessionStart hook to settings.json"
  else
    echo "[hook] SessionStart hook already exists, skipping"
  fi
fi

# 7. Load LaunchAgents
for label in "$LABEL_CHANNEL" "$LABEL_BOT"; do
  plist="$USER_HOME/Library/LaunchAgents/$label.plist"
  if launchctl list "$label" &>/dev/null; then
    launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
  fi
  launchctl bootstrap "gui/$(id -u)" "$plist" 2>/dev/null || true
  echo "[launchd] Loaded: $label"
done

echo "=== Install done ==="
